# Generated by GitHub Copilot on 2026-01-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scans/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('targetWidth', models.FloatField(default=8.0)),
                ('widthTolerance', models.FloatField(default=1.0)),
                ('targetHeight', models.FloatField(default=2.0)),
                ('heightTolerance', models.FloatField(default=0.5)),
                ('maxPorosity', models.IntegerField(default=0)),
                ('maxSpatter', models.IntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.JSONField(default=list)),
                ('distCoeffs', models.JSONField(default=list)),
                ('error', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
